// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH993VDRGL1pVOEnigqXmNZCaTHyn9-hc',
    appId: '1:357442872116:web:567d668450dce130efbb61',
    messagingSenderId: '357442872116',
    projectId: 'rappel-medicaments',
    authDomain: 'rappel-medicaments.firebaseapp.com',
    storageBucket: 'rappel-medicaments.firebasestorage.app',
    measurementId: 'G-KETVTS3NT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4oFy3Tjn-tK633fJZCHWSnfjSFP50UYg',
    appId: '1:357442872116:android:ab46c4831fc33ce7efbb61',
    messagingSenderId: '357442872116',
    projectId: 'rappel-medicaments',
    storageBucket: 'rappel-medicaments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSG7D3lclKOrRFiFDr_YzhI5xdpeaZ7IU',
    appId: '1:357442872116:ios:5e682b2255045075efbb61',
    messagingSenderId: '357442872116',
    projectId: 'rappel-medicaments',
    storageBucket: 'rappel-medicaments.firebasestorage.app',
    androidClientId: '357442872116-fnp5sqdl0sfcne7fesaln2n8u20rluej.apps.googleusercontent.com',
    iosClientId: '357442872116-9t88raugbg94fupnsapj4ebv5fmd5ud0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rappelMedicamentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSG7D3lclKOrRFiFDr_YzhI5xdpeaZ7IU',
    appId: '1:357442872116:ios:5e682b2255045075efbb61',
    messagingSenderId: '357442872116',
    projectId: 'rappel-medicaments',
    storageBucket: 'rappel-medicaments.firebasestorage.app',
    androidClientId: '357442872116-fnp5sqdl0sfcne7fesaln2n8u20rluej.apps.googleusercontent.com',
    iosClientId: '357442872116-9t88raugbg94fupnsapj4ebv5fmd5ud0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rappelMedicamentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH993VDRGL1pVOEnigqXmNZCaTHyn9-hc',
    appId: '1:357442872116:web:19485769a1a06adcefbb61',
    messagingSenderId: '357442872116',
    projectId: 'rappel-medicaments',
    authDomain: 'rappel-medicaments.firebaseapp.com',
    storageBucket: 'rappel-medicaments.firebasestorage.app',
    measurementId: 'G-0HCZ9EZ6N3',
  );
}
